//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurdurAdliyeEnvanterSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTONERSTOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLTONERSTOK()
        {
            this.TBLTONERCIKIS = new HashSet<TBLTONERCIKIS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MARKAID { get; set; }
        public Nullable<int> MODELID { get; set; }
        public Nullable<int> TONER { get; set; }
        public Nullable<int> DRUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTONERCIKIS> TBLTONERCIKIS { get; set; }
    }
}
