//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurdurAdliyeEnvanterSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTARAYICILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLTARAYICILAR()
        {
            this.TBLZIMMET = new HashSet<TBLZIMMET>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MARKAID { get; set; }
        public Nullable<int> MODELID { get; set; }
        public string SERINO { get; set; }
        public Nullable<bool> ZIMMET { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLMARKALAR TBLMARKALAR { get; set; }
        public virtual TBLMODELLER TBLMODELLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLZIMMET> TBLZIMMET { get; set; }
    }
}
