//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurdurAdliyeEnvanterSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLZIMMET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLZIMMET()
        {
            this.TBLTONERCIKIS = new HashSet<TBLTONERCIKIS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
        public Nullable<int> BILGISAYARID { get; set; }
        public Nullable<int> YAZICIID { get; set; }
        public Nullable<int> TARAYICIID { get; set; }
        public string DOMAINADI { get; set; }
        public string YAZICIIP { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLBILGISAYARLAR TBLBILGISAYARLAR { get; set; }
        public virtual TBLPERSONELLER TBLPERSONELLER { get; set; }
        public virtual TBLTARAYICILAR TBLTARAYICILAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTONERCIKIS> TBLTONERCIKIS { get; set; }
        public virtual TBLYAZICILAR TBLYAZICILAR { get; set; }
    }
}
